version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: telegram-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/telegram_analyzer/uploads:/app/telegram_analyzer/uploads
      - ./backend/telegram_analyzer/db:/app/telegram_analyzer/db
    environment:
      FLASK_APP: telegram_analyzer/app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: telegram-frontend
    ports:
      - "3000:3000"
    environment:
      NUXT_PORT: 3000
    depends_on:
      - backend
    restart: unless-stopped
